"""Minimal PythonSCAD 1.1 API used for this project's static checks."""

from collections.abc import Sequence

class PyOpenSCAD:
    def translate(self, vector: Sequence[float]) -> PyOpenSCAD: ...
    def down(self, distance: float) -> PyOpenSCAD: ...
    def __sub__(self, other: PyOpenSCAD) -> PyOpenSCAD: ...

def cube(size: Sequence[float]) -> PyOpenSCAD: ...
def cylinder(*, d: float, h: float, fn: int) -> PyOpenSCAD: ...
